server {
    listen 8084;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Critical for React Routing
    }

    # Cache static assets for PWA performance
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|json)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Do not cache the service worker
    location = /sw.js {
        root /usr/share/nginx/html;
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }
}
